import { NextResponse } from "next/server";

const shopProducts = [
  {
    id: 1,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    image: "/images/productsimages/product-six.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 2,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-seven.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 3,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-one.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 4,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 5,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-two.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 6,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-three.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 7,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-four.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 8,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-eight.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 9,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-nine.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 10,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-ten.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 11,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-eleven.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
  {
    id: 12,
    name: "Graphic Design",
    department: "English Department",
    price: "$16.48",
    pricetwo: "$16.48",
    image: "/images/productsimages/product-twelve.png",
    colors: [
      { name: "Sky Blue", colorClass: "bg-primaryColor" },
      { name: "Green", colorClass: "bg-secondColorOne" },
      { name: "Orange", colorClass: "bg-alertColor" },
      { name: "Sky Blue", colorClass: "bg-textColor" },
    ],
  },
];

export async function GET() {
  return NextResponse.json(shopProducts);
}
